# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

############
# lib
############
lib_path = os.path.join(cwd, os.pardir, os.pardir, 'lib')

lib_sconscript = os.path.join(lib_path, 'SConscript')
objs = objs + SConscript(lib_sconscript)
############

Return('objs')
