import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
lib_sub_sconscript = []
list = os.listdir(cwd)

src = Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('base_lib', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')