from building import *
import os

cwd = GetCurrentDir()
src = Glob('src/base/*.cpp') + Glob('src/*.cpp')
CPPPATH = [cwd,'src/base', 'src', 'include', 'include/uorb']

group = DefineGroup('uorb', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
